CREATE DATABASE SEM01 
ON 
(
NAME=NOMBRELOGICO_ARCHIVO , 
FILENAME=RUTA DEL ARCHIVO EN FISICO, 
SIZE=TAMANO INICIAL EN MB SI N0 SE ESPECIFICA,
MAXSIZE=TAMANO MAXIMO O SI N0 SE TIENE UNLIMITED,
FILEGROWTH=TASA DE CRECIMIENTO EN % O EN MB
)

GO

CREATE DATABASE BD_EJEMPLO GO 
SP_HELPDB BD_EJEMPLO GO -- SIRVE PARA VISUALIZAR LAS CARACTERISTICAS DE LOS 
						--ARCHIVOS DE LA BASE DE DATOS--
IF DB_ID('BD_EJEMPLO') IS NOT NULL 
BEGIN 
	DROP DATABASE BD_EJEMPLO
END
GO

EJEMPLO 01

IF DB_ID('BD_COMERCIAL')IS NOT NULL
BEGIN
	DROP DATABASE BD_COMERCIAL
END 
GO

CREATE DATABASE BD_COMERCIAL
ON
(
	NAME=BD_COMERCIAL_PRI,
	FILENAME= 'C:\BASE DE DATOS\BD_COMERCIAL\BD_COMERCIAL.MDF',
	SIZE=50,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=10%
)
GO
SP_HELPDB BD_COMERCIAL
GO

EJEMPLO 02

IF DB_ID('COMERCIAL2017')IS NOT NULL
BEGIN
	DROP DATABASE COMERCIAL2017
END
GO
CREATE DATABASE COMERCIAL2017
ON
(
	NAME=COMERCIAL_PRI,
	FILENAME='C:\BASE DE DATOS\COMERCIAL\DATA\COMERCIAL_PRI.MDF',
	SIZE=40MB,
	MAXSIZE=250MB,
	FILEGROWTH=5MB
)
LOG ON
(
	NAME=COMERCIAL_TRA,
	FILENAME='C:\BASE DE DATOS\COMERCIAL\LOG\COMERCIAL_TRA.LDF',
	SIZE=10,
	MAXSIZE=50,
	FILEGROWTH=5%
)
GO
SP_HELPDB COMERCIAL2017
GO



EJEMPLO 03

IF DB_ID('BD_TIENDA')IS NOT NULL
BEGIN
	DROP DATABASE BD_TIENDA
END
GO
CREATE DATABASE BD_TIENDA
ON
(
	NAME=BD_TIENDA_PRI,
	FILENAME='C:\BASE DE DATOS\BD_TIENDA\DATA\BD_TIENDA_PRI.MDF',
	SIZE=100MB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=15%
),
(
	NAME=BD_TIENDA_SEC,
	FILENAME='C:\BASE DE DATOS\BD_TIENDA\SEC\BD_TIENDA_SEC.NDF',
	SIZE=50MB,
	MAXSIZE=250MB,
	FILEGROWTH=10%
)
LOG ON 
(
	NAME=BD_TIENDA_TRA,
	FILENAME='C:\BASE DE DATOS\BD_TIENDA\LOG\BD_TIENDA_TRA.LDF',
	SIZE=5MB,
	MAXSIZE=50MB,
	FILEGROWTH=5MB
)

GO
SP_HELPDB BD_TIENDA
GO

EJEMPLO 04 UTILIZANDO MODIFICACIONES ALT4R



USE MASTER 
GO
ALTER DATABASE BD_TIENDA
MODIFY NAME=MINIMARKET
GO

ANADIR ARCHIVOS SECUNDARIOS A LA BASE DE DATOS COMERCIAL 2017

ALTER DATABASE COMERCIAL2017

ADD FILE
(
NAME=COMERCIAL_SEC1,
FILENAME='C:\BASE DE DATOS\COMERCIAL\SEC1.NDF',
SIZE=10,
MAXSIZE=50,
FILEGROWTH=10%
),
(
NAME=COMERCIAL_SEC2,
FILENAME='C:\BASE DE DATOS\COMERCIAL\SEC\SEC2.NDF',
SIZE=10,
MAXSIZE=100,
FILEGROWTH=15%
)

GO
SP_HELPDB COMERCIAL2017
GO

ELIMINAR ARCHIVOS SECUNDARIOS DE UNA BASE DE DATOS


USE MASTER
ALTER DATABASE COMERCIAL2017
REMOVE FILE COMERCIAL_SEC2
GO

VERIFICAR QUE EL ARCHIVO HAYA SIDO ELIMINADO

GO
SP_HELPDB COMERCIAL2017
GO

ELIMINAR BASE DE DATOS
USE MASTER
DROP DATABASE COMERCIAL2017
GO


ELIMINAR BASE DE DATOS VALIDANDO LA EXISTENCIA DE SI MISMA


USE MASTER
IF DB_ID('BD_COMERCIAL')IS NOT NULL
	DROP DATABASE BD_COMERCIAL
GO

EJERCICIOS INTEGRADORESSSS , VAMOS FAMILIARIZANDONOSSSSSS <3

EJERCICIO01-

USE MASTER
IF DB_ID('BD_MAQUINARIAS')IS NOT NULL
DROP DATABASE BD_MAQUINARIAS
GO
CREATE DATABASE BD_MAQUINARIAS
ON
(
NAME=BD_MAQUINARIAS_PRI,
FILENAME='C:\BASE DE DATOS\MAQUINARIAS\DATA\BD_MAQUINARIAS_PRI.MDF',
SIZE=10MB,
MAXSIZE=100MB,
FILEGROWTH=10%
),
(
NAME=BD_MAQUINARIAS_SEC,
FILENAME='C:\BASE DE DATOS\MAQUINARIAS\DATA\BD_MAQUINARIAS_SEC.NDF',
SIZE=5,
MAXSIZE=50,
FILEGROWTH=10%
)
LOG ON
(
NAME=BD_MAQUINARIAS_TRA,
FILENAME='C:\BASE DE DATOS\MAQUINARIAS\DATA\BD_MAQUINARIAS_TRA.LDF',
SIZE=5,
MAXSIZE=40,
FILEGROWTH=10%
)

GO
SP_HELPDB BD_MAQUINARIAS
GO

USE MASTER
ALTER DATABASE BD_MAQUINARIAS
MODIFY FILE(NAME='BD_MAQUINARIAS_TRA' ,  SIZE=10 ,  FILEGROWTH=15%)
GO

ALTER DATABASE BD_MAQUINARIAS
ADD FILE
(
NAME = BD_MAQUINARIAS1,
FILENAME = 'C:\BASE DE DATOS\MAQUINARIAS\SEC\BD_MAQUINARIAS1.NDF',
SIZE=5,
MAXSIZE=20
),
(
NAME=BD_MAQUINARIAS2,
FILENAME = 'C:\BASE DE DATOS\MAQUINARIAS\SEC\BD_MAQUINARIAS2.NDF',
SIZE=5,
MAXSIZE=20
),
(
NAME=BD_MAQUINARIAS3,
FILENAME = 'C:\BASE DE DATOS\MAQUINARIAS\SEC\BD_MAQUINARIAS3.NDF',
SIZE=5,
MAXSIZE=20
)

GO 
SP_HELPDB BD_MAQUINARIAS
GO

USE MASTER 
ALTER DATABASE BD_MAQUINARIAS
REMOVE FILE BD_MAQUINARIAS2
GO

CASOPROPUESTO 01 INSTITUTO

